[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
splcards = "6jPXVk78mLJq3MAz24gasxmYmV2f3bYDd5Rp5zK92tew"

[programs.devnet]
splcards = "6jPXVk78mLJq3MAz24gasxmYmV2f3bYDd5Rp5zK92tew"

[programs.mainnet]
splcards = "6jPXVk78mLJq3MAz24gasxmYmV2f3bYDd5Rp5zK92tew"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nielsoskam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
